
title: Aishwarya Chennabathni
description: "Data Scientist"
logo: /202408111541019602.jpg
#description: Minimal is a theme for GitHub Pages.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
